### ISSUE TITLE
Manifest requires msmart 0.2.4 which is not available in PyPi

### ISSUE THREAD

**Issue by mill1000** [0xbw/midea-ac-py#183]
The current manifest requires msmart 0.2.4 which is [not available in PyPi](https://pypi.org/project/msmart/#history). This is causing install failures for users (reported in #182) because the dependency can not be met.

https://github.com/mac-zhou/midea-ac-py/blob/a1699f714e4113ccd25f8f32f2d245781ce654fc/custom_components/midea_ac/manifest.json#L7

We should bump the manifest version to 0.2.5 or merge #178 to support multiple versions.

**Comment by AndoKarim** [comment]
I bumped the manifest version and the behavior with my AC is totally different. I don't have all the controls when using the classic card. 
I got those errors when trying to interract : 
"error set_hvac_mode"

**Comment by mill1000** [comment]
That is likely because of mac-zhou/midea-msmart#90. Unfortunately this integration is currently in a bit of a bad state.

I've got a branche with a number of fixes merged here: [mill1000/midea-msmart](https://github.com/mill1000/midea-msmart/tree/future).

To install via pip
```
pip install git+https://github.com/mill1000/midea-msmart.git
```

**Comment by AndoKarim** [comment]
So I'm using the latest version of midea-ac-py and your fork / branche and I still have those issues : 
![image](https://user-images.githubusercontent.com/11462704/181804246-0f0352aa-2c84-46b0-95e5-40d9b2b955e6.png)


and the sensors are at 0C 
![image](https://user-images.githubusercontent.com/11462704/181804292-a38d16bd-a348-42cb-a4c0-c77ceb410312.png)

This is my manifest : 
![image](https://user-images.githubusercontent.com/11462704/181804338-8b792a4d-2a7d-48bb-a4d3-919084d11a7c.png)

And if I add the configuration too in the configuration.yaml : 
![image](https://user-images.githubusercontent.com/11462704/181804743-3a8e0732-c40f-4187-bb70-ec262fa0b9b9.png)

**Comment by mill1000** [comment]
To me it looks like HA is still using the old version of midea-msmart because the `get_capabilities` call is missing. I've had issues where HA doesn't update the requirements even if the manifest changes. Can you manually install the dependency via pip?

**Comment by AndoKarim** [comment]
pip is not working on my end, I replied to you on the other issue you're following. Maybe we can stick to this one? 

![image](https://user-images.githubusercontent.com/11462704/181805416-8179f7d7-a2d4-4c8b-958e-963a09e013e4.png)
I cannot use any command in Terminal

**Comment by AndoKarim** [comment]
Update: 
I ended up discovering there is two Terminal modules. 
I installed the right one. I'm trying to pip install your branche

Update: Still the same error after doing 
pip install git+https://github.com/mill1000/midea-msmart.git@future

**Comment by mill1000** [comment]
Great. I was just about to reply to see if you were using this [add-on](https://github.com/hassio-addons/addon-ssh) or other "official" one. The official one seems quite limited in its use

**Comment by AndoKarim** [comment]
Yeah I solved the ssh issue but still stuck with this msmart.

I removed the requirements from manifest.json. But still having the same issue, not finding _get_capabilities_ 
I even did pip uninstall msmart and reinstalled the 0.2.4, tried the 0.2.5 official and your fork.. 

I am missing something but don't know why. It seems there is a sneaky msmart that is still installed somewhere and grabbing my midea-ac-py

**Comment by mill1000** [comment]
If you're getting issues with `get_capabilities`, then it sounds like you're installing msmart...at least not where HA is looking for it.

Are you running these pip commands within the Docker container that runs HA?

**Comment by AndoKarim** [comment]
I am running the pip install from the root it seems

**Comment by AndoKarim** [comment]
Ok I fixed the issue here are the steps : 

Open a terminal and enter in docker mode : 
- docker exec -it homeassistant bash (you need to disable protected mode from Terminal module)
- Then do a pip uninstall msmart (I had version 0.2.3 installed)
- I did a pip install of the 0.2.4 commit of mac-zhou 

Everything came back in track. 

The mistake here is to use Terminal and connect as root and do the steps. **You need to be in the docker**

Thanks a lot for your help.

**Comment by mill1000** [comment]
No problem. Glad you got it working again.

If it's of interest to you. I also have a future branch of midea-ac-py [here ](https://github.com/mill1000/midea-ac-py/tree/future) that add some additional features
